todo/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('todos/', include('todo.urls')),
    path('admin/', admin.site.urls),
]

todo/mysite/todo/urls.py
from django.urls import path

from . import views

app_name = 'todos'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.TodoView.as_view(), name='detail'),
    path('<int:todo_id>/complete/', views.complete, name='complete'),
]

todo/mysite/todo/models.py
from django.db import models


class Todo(models.Model):
    todo_name = models.CharField(max_length=50)
    todo_description = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date created')
    todo_open = models.BooleanField(default=True)
    def __str__(self):
        return self.todo_name

class Task(models.Model):
    todo = models.ForeignKey(Todo, on_delete=models.CASCADE)
    task_description = models.CharField(max_length=200)
    task_complete = models.BooleanField(default=False)
    pub_date = models.DateTimeField('date added')
    def __str__(self):
        return self.task_description

todo/mysite/todo/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Todo


class IndexView(generic.ListView):
    template_name = 'todo/index.html'
    context_object_name = 'latest_todo_list'

    def get_queryset(self):
        return Todo.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class TodoView(generic.DetailView):
    model = Todo
    template_name = 'todo/detail.html'
    def get_queryset(self):
        return Todo.objects.filter(pub_date__lte=timezone.now())

def complete(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    try:
        selected_task = todo.task_set.get(pk=request.POST['task'])
    except (KeyError, Todo.DoesNotExist):
        return render(request, 'todo/detail.html', {
            'todo': todo,
            'error_message': "You didn't select a task to mark as complete.",
        })
    else:
        selected_task.task_complete = not selected_task.task_complete
        selected_task.save()
        return HttpResponseRedirect(reverse('todos:detail', args=(todo_id,)))

todo/mysite/todo/templates/todo/detail.html
<h1>{{ todo.todo_name }}</h1>
<h3>{{ todo.todo_description }}</h3>
<h6>Active: {{ todo.todo_open }}</h6>

<ul>
  {% for task in todo.task_set.all %} {% if task.task_complete %}
  <li>
    <h5 style="text-decoration: line-through">{{ task.task_description }}</h5>
  </li>
  {% else %}
  <li><h5>{{ task.task_description }}</h5></li>
  {% endif %} {% endfor %}
</ul>

{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'todos:complete' todo.id %}" method="post">
  {% csrf_token %} {% for task in todo.task_set.all %}
  <input
    type="radio"
    name="task"
    id="task{{ forloop.counter }}"
    value="{{ task.id }}"
  />
  <label for="task{{ forloop.counter }}">{{ task.task_description }}</label
  ><br />
  {% endfor %}
  <input type="submit" value="Toggle" />
</form>

todo/mysite/todo/templates/todo/index.html
{% if latest_todo_list %}
<ul>
  {% for todo in latest_todo_list %}
  <li>
    <a href="{% url 'todos:detail' todo.id %}">{{ todo.todo_name }}</a>
  </li>
  {% endfor %}
</ul>
{% else %}
<p>No todo's are available.</p>
{% endif %}